version: '3'

name: email_sms_project
services:
  backend:
    container_name: email_sms_project_backend
    build:
      context: .
      dockerfile: Docker/django/Dockerfile
    command: bash -c "/usr/src/app/entrypoint.sh"
    volumes:
      - .:/app
    ports:
      - "8005:8000"
    env_file:
      - .env
    networks:
      - common-net
networks:
  common-net:
    external: true